### ISSUE TITLE
Get comments for image id

### ISSUE THREAD

**Issue by knatola** [ppeerttu/instagram-clone#32]
Implement api for returning all comments for an image id.
Implementation for both
- rest-api
- comment-service

The api should support paging.

**Comment by ppeerttu** [comment]
This feature is mentioned also in #29, please report back to it when it's done. The API should be **GET** `/images/:id/comments` right?

Also, I think the **POST** `/comments` API could be moved to **POST** `/images/:id/comments`, thoughts?

**Comment by knatola** [comment]
True, true I'll just remove this and i'll move endpoint in the same pr
